name: Update README Badge

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update README with a fresh timestamp
        run: |
          sed -i "s|https://custom-icon-badges.demolab.com/youtube/channel/subscribers/UC2Soj_Sfe_rUzBytOug0qwA[^)]*|https://custom-icon-badges.demolab.com/youtube/channel/subscribers/UC2Soj_Sfe_rUzBytOug0qwA?color=%23E05D44&label=SUBSCRIBE&logo=video&logoColor=white&style=for-the-badge&labelColor=CE4630&timestamp=$(date +%s)|g" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated YouTube badge timestamp" || exit 0
          git push
